language: r

warnings_are_errors: true

matrix:
  include:
   - r: release
     before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
   - r: devel
   - r: oldrel

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  webhooks:
    urls:
      - https://api.netlify.com/build_hooks/5c485816b40a5a017096df38
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
